# Generated by Django 5.0.1 on 2024-02-10 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('customer_id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('customer_name', models.CharField(max_length=20)),
                ('customer_last_name', models.CharField(max_length=30)),
                ('customer_email', models.EmailField(max_length=50)),
                ('customer_phone', models.CharField(max_length=10)),
                ('customer_address', models.CharField(max_length=50)),
                ('customer_city', models.CharField(max_length=30)),
            ],
        ),
    ]
