# Generated by Django 5.0.1 on 2024-02-10 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_customers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='customer_img',
            field=models.ImageField(blank=True, null=True, upload_to='backend/main/static/customers'),
        ),
    ]
