# Generated by Django 5.0.1 on 2024-02-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_customers_customer_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='customer_active',
            field=models.BooleanField(default=True),
        ),
    ]
